apiVersion: v1
kind: Deployment
metadata:
  name: demo-service-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: dockerjavagcp
    spec:
      containers:
        - name: dockerjavagcp
          image: gcr.io/cognitivebot2/dockerjavagcp
          ports:
            - containerPort: 8090